# Runs on release

name: Publish Release
on:
  release:
    types: [published]
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push image to dockerhub
    permissions:
      contents: write
      pull-requests: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: inventree/inventree-caddy:latest, inventree/inventree-caddy:${{ github.event.release.tag_name }}
